### ISSUE TITLE
Epic: Update material selection

### ISSUE THREAD

**Issue by ranzwertig** [all3dp/printing-engine-client#937]
- [ ] Add the new layout
- [ ] Create the card component for the sidebar
- [ ] Provide a variant for the "edit from the checkout view"-process (cancel, ..)
